mutation createYTVideoStream(
  $url: String!
  $name: String!
  $parent_resource: ID!
  $parent_resource_type: String!
  $assignment: Boolean
) {
  createYTVideoStream(
    url: $url
    name: $name
    parent_resource: $parent_resource
    parent_resource_type: $parent_resource_type
    assignment: $assignment
  ) {
    _id
    url
    name
    type
    parent_resource {
      ... on SharedResource {
        _id
        name
        type
      }
    }
    parent_resource_type
  }
}
