query lecture($_id: ID!) {
  lecture(_id: $_id) {
    _id
    name
    type
    start
    end
    auths {
      _id
      role
      user {
        _id
        name
        email
        first_name
        last_name
      }
    }
    parent_resource {
      ... on SharedResource {
        _id
        name
        type
      }
    }
    parent_resource_type
    recording {
      ... on VideoStream {
        _id
        url
        type
        duration
        checkins {
          _id
          type
          tickets {
            _id
            first_name
            last_name
            code
            user
          }
        }
        assignment {
          _id
          submissions {
            _id
            submittable {
              ... on VideoStreamPlayback {
                _id
                seconds_watched
                creator {
                  _id
                  name
                  email
                }
              }
            }
            submittable_type
          }
        }
      }
    }
    recording_type
    checkins {
      _id
      type
      tickets {
        _id
        first_name
        last_name
        code
        user
      }
    }
  }
}
