query me {
  me {
    _id
    first_name
    last_name
    name
    email
    bottts
    created_at
    updated_at
    auths {
      _id
      role
      user {
        _id
        name
        email
      }
      shared_resource {
        _id
        name
        type
        parent_resource {
          ... on SharedResource {
            _id
            name
            type
          }
          ... on User {
            _id
            name
            type
          }
        }
        parent_resource_type
      }
      shared_resource_type
    }
  }
}
