fragment RegistrationSection on RegistrationSection {
  _id
  name
  auths {
    _id
    role
  }
  user_groups {
    _id
    name
    auths {
      _id
      role
    }
  }
  lectures {
    _id
    name
    start
    end
    auths {
      _id
      role
      user {
        _id
        name
        first_name
        last_name
        email
      }
    }
    parent_resource {
      ... on SharedResource {
        _id
        name
        type
      }
    }
    parent_resource_type
  }
  meeting_times {
    weekday
    event {
      name
      start
      end
    }
  }
}
